from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="Listing", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("title", models.CharField(max_length=200)), ("description", models.TextField()), ("price", models.DecimalField(decimal_places=2, max_digits=8)), ("original_price", models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)), ("category", models.CharField(choices=[("textbooks", "Textbooks"), ("electronics", "Electronics"), ("furniture", "Furniture"), ("clothing", "Clothing"), ("other", "Other")], max_length=20)), ("condition", models.CharField(choices=[("new", "New"), ("like_new", "Like New"), ("good", "Good"), ("fair", "Fair")], max_length=20)), ("listing_type", models.CharField(choices=[("sell", "Sell"), ("rent", "Rent")], default="sell", max_length=10)), ("status", models.CharField(choices=[("active", "Active"), ("sold", "Sold"), ("reserved", "Reserved")], default="active", max_length=10)), ("is_price_firm", models.BooleanField(default=False)), ("pickup_only", models.BooleanField(default=False)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("seller", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="listings", to=settings.AUTH_USER_MODEL))], options={"ordering": ["-created_at"]}),
        migrations.CreateModel(name="ListingImage", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("image", models.ImageField(upload_to="listings/%Y/%m/")), ("is_primary", models.BooleanField(default=False)), ("order", models.PositiveIntegerField(default=0)), ("listing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="marketplace.listing"))], options={"ordering": ["order"]}),
        migrations.CreateModel(name="SavedListing", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("saved_at", models.DateTimeField(auto_now_add=True)), ("listing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="saved_by", to="marketplace.listing")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="saved_listings", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="Conversation", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("updated_at", models.DateTimeField(auto_now=True)), ("buyer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="purchases", to=settings.AUTH_USER_MODEL)), ("listing", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="conversations", to="marketplace.listing")), ("seller", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="sales_chats", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="Message", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("body", models.TextField(max_length=2000)), ("created_at", models.DateTimeField(auto_now_add=True)), ("is_read", models.BooleanField(default=False)), ("conversation", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="messages", to="marketplace.conversation")), ("sender", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL))], options={"ordering": ["created_at"]}),
        migrations.AddConstraint(model_name="savedlisting", constraint=models.UniqueConstraint(fields=("user", "listing"), name="unique_saved_listing")),
        migrations.AddConstraint(model_name="conversation", constraint=models.UniqueConstraint(fields=("listing", "buyer", "seller"), name="unique_listing_conversation")),
    ]
